#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"
echo $HERE

export GST_PLUGIN_SCANNER=$(readlink -f $(dirname "$0")/usr/lib/gst-plugin-scanner)
export GST_PLUGIN_SYSTEM_PATH=$(readlink -f $(dirname "$0")/usr/lib)

${APPDIR}/usr/bin/feather $*
