#ifndef FEATHER_VERSION_H
#define FEATHER_VERSION_H

#define FEATHER_VERSION "@PROJECT_VERSION@"
#define FEATHER_COMMIT "@FEATHER_COMMIT@"

#define TOR_VERSION "@TOR_VERSION@"

#endif //FEATHER_VERSION_H
