#ifndef FEATHER_VERSION_H
#define FEATHER_VERSION_H

#define FEATHER_VERSION "@PROJECT_VERSION@"

#define TOR_VERSION "@TOR_VERSION@"

#define FEATHER_TARGET_TRIPLET "@FEATHER_TARGET_TRIPLET@"

#endif //FEATHER_VERSION_H
