#ifndef FEATHER_VERSION_H
#define FEATHER_VERSION_H

#define FEATHER_VERSION "@VERSION@"
#define FEATHER_BRANCH "@FEATHER_BRANCH@"

#define MONERO_VERSION "@MONERO_VERSION@"
#define MONERO_BRANCH "@MONERO_BRANCH@"

#endif //FEATHER_VERSION_H
