find_path(POLYSEED_INCLUDE_DIR polyseed.h)
find_library(POLYSEED_LIBRARY NAMES libpolyseed.a polyseed)
if (NOT POLYSEED_INCLUDE_DIR OR NOT POLYSEED_LIBRARY)
    MESSAGE(STATUS "Could not find installed Polyseed, using submodule instead")
    set(Polyseed_SUBMODULE "ON")
    set(POLYSEED_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/src/third-party/polyseed/include)
    set(POLYSEED_LIBRARY polyseed_static)
endif()
message(STATUS "POLYSEED PATH ${POLYSEED_INCLUDE_DIR}")
message(STATUS "POLYSEED LIBARY ${POLYSEED_LIBRARY}")